version: "1.0"
info:
  model: int-scaffold
packages:
- name: JMSJNDDIAllrSIQAtestProject
  gitServerName: RajniVCAccount
  gitUrl: https://github.com/Rajni25Aug
  gitUsername: Rajni25Aug
  gitBranch: main
